version: "3.7"
services:
  web:
    image: "jairbj/vscode-ruby:2.6.3"
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
      # - "./.gem:/usr/local/bundle"    
    command: "/bin/bash"
    tty: true
    networks:
      - convinet
    depends_on:
      - db
      - redis
  db:
    image: "mariadb:latest"
    ports: 
      - "3306:3306"
    volumes:
      - "./.mysql:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
    networks:
      - convinet
    command:
      'mysqld --innodb-flush-method=fsync'
  redis:
    image: "redis:latest"
    networks:
      - convinet
    ports: 
      - "6379:6379"    
networks:
  convinet:
    driver: bridge